name: Puppeteer Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install system dependencies for Puppeteer
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libnss3 \
          libatk-bridge2.0-0 \
          libxss1 \
          libgconf-2-4 \
          libgtk-3-0 \
          libx11-xcb1 \
          libdbus-glib-1-2 \
          libxtst6 \
          libxss1 \
          fonts-liberation \
          libappindicator3-1 \
          libasound2

    - name: Install dependencies
      run: npm install

    - name: Run Puppeteer tests
      run: |
        if ! node src/tests/extension-test.js; then
          echo "Tests failed. Stopping merge."
          exit 1
        fi

    - name: Success Message
      if: ${{ success() }}
      run: echo "All tests passed successfully!"
