name: Puppeteer Tests

on:
  push:  # Triggers on any push to any branch
    branches:
      - '**'  # Match all branches

  pull_request:  # Triggers on pull requests to any branch
    branches:
      - '**'  # Match all branches

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify your Node.js version

    - name: Install system dependencies for Puppeteer
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libnss3 \
          libatk-bridge2.0-0 \
          libxss1 \
          libgconf-2-4 \
          libgtk-3-0 \
          libx11-xcb1 \
          libdbus-glib-1-2 \
          libxtst6 \
          libxss1 \
          fonts-liberation \
          libappindicator3-1 \
          libasound2

    - name: Install dependencies
      run: npm install  # Install your project's dependencies

    - name: Run Puppeteer tests
      run: node src/tests/extension-test.js  # Use your specific command

    - name: Check test results
      if: ${{ failure() }}
      run: echo "Tests failed. Check the logs for details."  # Log if tests fail

    - name: Success Message
      if: ${{ success() }}
      run: echo "All tests passed successfully!"  # Log if tests pass
